# Generated by Django 5.1.2 on 2024-10-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_restaurant_external_reviews_url_restaurant_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='photo',
            new_name='secondary_image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/'),
        ),
    ]
