# Generated by Django 5.1.2 on 2024-10-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_restaurant_reviews_alter_restaurant_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date_posted',
            new_name='created_at',
        ),
    ]
